#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running pre-commit checks..."

## prettier

npm run prettier

if git diff --cached --name-only | grep -E '\.ts$' > /dev/null; then
  npm run types
else
  echo "No TypeScript files to check, skipping types."
fi

npm run lint