name: Security Checks

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get base commit
        id: base
        run: |
          echo "BASE_COMMIT=$(git merge-base origin/${{ github.base_ref || 'main' }} HEAD)" >> "$GITHUB_OUTPUT"

      - name: Secret Scanning
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --since-commit=${{ steps.base.outputs.BASE_COMMIT }} --results=verified,unknown,unverified --no-verification --json