name: Security Checks

on:
  push:
  pull_request:

jobs:
  scan-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run TruffleHog scan for secrets
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: >-
            --branch=${{ github.head_ref || github.ref_name }}
            --results=verified,unknown,unverified
            --no-verification
            --json
